version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: ember-template-lint
    versions:
    - 3.0.0
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-auto-import
    versions:
    - 1.11.0
    - 1.11.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.24.0
    - 7.25.0
    - 7.26.0
    - 7.26.1
    - 7.26.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.4.0
    - 5.5.0
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-concurrency
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.1
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
